// template-react-frontend/src/components/frame/WindowFrame.js
import {ArrowForward} from "@mui/icons-material";
import {Routes} from "react-router-dom";
import {createRoute} from "../../rounter";
import {getAccessToken, removeAccessToken} from "../../utils/cacheManager";
import {useDispatch, useSelector} from "react-redux";
import {setSidebarExpanded} from "../../store/sidebarSlice";
import {useEffect} from "react";
import {logoutApi, metadataApi} from "../../api/userApi";
import {setPersonName} from "../../store/personNameSlice";
import SidebarItem from "./SidebarItem";
import styled from "styled-components";
import {colorBlueDark, colorOrange, colorOrangeDark, colorOrangeDarker} from "../../utils/constant";
import {createTheme, ThemeProvider} from "@mui/material";

const RootWindow = styled.div`
    display: flex;
    width: 100%;
    height: 100vh;
    word-wrap: break-word;
`

const Sidebar = styled.div`
    display: inline-block;
    width: ${props => {
        return props.expanded ? "30rem" : "5rem"
    }};
    height: 100%;
    background-color: #5982B6;
    box-shadow: 0.1rem 0 0.2rem #666666;
    transition-duration: 0.5s;
    z-index: 100;
`

const SidebarToggleButtonWrapper = styled.div`
    width: 100%;
    height: 5rem;
`

const SidebarToggleButton = styled.div`
    float: right;
    display: block;
    width: 5rem;
    height: 5rem;
    transform: ${props => {
        return props.flipped ? "rotateY(180deg)" : "none"
    }};
    transition-duration: 0.5s;
    &:hover {
        cursor: pointer;
        background-color: ${() => colorBlueDark};
    }
`

const TopBar = styled.div`
    display: flex;
    height: 5rem;
    padding-left: 5px;
    background-color: ${() => colorOrange};
    box-shadow: 0 0.1rem 0.2rem #666666;
`

const PersonName = styled.div`
    display: flex;
    width: fit-content;
    height: 100%;
    font-size: 1.8rem;
    align-items: center;
`

const Hello = styled.div`
    font-size: 1.5rem;
`

const PersonNameText = styled.div`
    font-weight: bold;
    text-align: center;
`

const LogoutButton = styled.div`
    position: absolute;
    display: flex;
    right: 1rem;
    width: fit-content;
    height: 5rem;
    align-items: center;
    padding: 0 1rem;
    font-size: 1.5rem;
    &:hover {
        cursor: pointer;
        background-color: ${() => colorOrangeDark};
    }
    &:active {
        background-color: ${() => colorOrangeDarker};
    }
`

const Content = styled.div`
    position: relative;
    display: inline-block;
    //width: calc(100% - 30rem);
    width: ${props => {
        return props.stretched ? "calc(100% - 5rem)" : "calc(100% - 30rem)"
    }};
    height: 100%;
    transition-duration: 0.5s;
`

const RouteContent = styled.div`
    position: absolute;
    left: 0;
    top: 5rem;
    right: 0;
    bottom: 0;
    padding: 5px;
`

const sidebarToggleArrowTheme = createTheme({
    components: {
        MuiSvgIcon: {
            styleOverrides: {
                root: {
                    width: "3rem",
                    height: "3rem",
                    margin: "1rem",
                    color: colorOrange
                }
            }
        }
    }
});

export default function WindowFrame(props) {
    const sidebarExpanded = useSelector(state => state.sidebar.sidebarExpanded);
    const accessToken = getAccessToken();
    const dispatch = useDispatch();

    function onSidebarToggle() {
        dispatch(setSidebarExpanded(!sidebarExpanded));
    }

    useEffect(() => {
        metadataApi().then(response => {
            dispatch(setPersonName({
                firstName: response.resultBody.firstName,
                lastName: response.resultBody.lastName
            }));
        }).catch(() => {});
    }, [dispatch]);

    function usePersonName() {
        let personName = useSelector(state => state.personName);
        return (personName.firstName ? personName.firstName : "") +
            (personName.lastName ? " " + personName.lastName : "");
    }

    function logout() {
        logoutApi().then(() => {
            removeAccessToken();
            window.location.reload();
        }).catch(() => {});
    }
    let menuTree = useSelector(state => state.menu.menuTree);

    return <RootWindow>
        <Sidebar expanded={sidebarExpanded}>
            <SidebarToggleButtonWrapper>
                <SidebarToggleButton flipped={sidebarExpanded} onClick={onSidebarToggle}>
                    <ThemeProvider theme={sidebarToggleArrowTheme}>
                        <ArrowForward/>
                    </ThemeProvider>
                </SidebarToggleButton>
            </SidebarToggleButtonWrapper>
            <SidebarItem items={menuTree} indent={2} parentKey={0}/>
        </Sidebar>
        <Content stretched={!sidebarExpanded}>
            <TopBar>
                <PersonName>
                    <Hello>Hello,&nbsp;</Hello>
                    <PersonNameText>{ usePersonName() }</PersonNameText>
                </PersonName>
                <LogoutButton onClick={logout}>Logout</LogoutButton>
            </TopBar>
            <RouteContent>
                <Routes>
                    { props.children.map((child, index) => createRoute(child, index, accessToken)) }
                </Routes>
            </RouteContent>
        </Content>
    </RootWindow>
}

// template-vue-frontend/src/components/frame/WindowFrame.vue
<script setup lang="ts">
import { useSidebarStore } from '@/stores/sidebar'
import { storeToRefs } from 'pinia'
import { useMenuStore } from '@/stores/menu'
import SidebarItem from '@/components/frame/SidebarItem.vue'
import { ArrowLeft } from '@element-plus/icons-vue'
import { usePersonStore } from '@/stores/person'
import { onBeforeMount } from 'vue'
import { logoutApi, metadataApi } from '@/api/userApi'
import { removeAccessToken } from '@/utils/cacheManager'

const sidebarStore = useSidebarStore()
const { sidebarExpanded } = storeToRefs(sidebarStore)

const personStore = usePersonStore()

const toggleSidebar = () => {
  sidebarStore.toggleSidebar()
}

const getFullName = () => {
  const personName = personStore.personName

  return (personName.firstName ? personName.firstName : '') +
    (personName.lastName ? (' ' + personName.lastName) : '')
}

const logout = () => {
  logoutApi()
    .then(() => {
      removeAccessToken()
      window.location.reload()
    })
}

onBeforeMount(() => {
  if (!personStore.personName.firstName && !personStore.personName.lastName) {
    metadataApi()
      .then(response => {
      personStore.setPersonName({
        firstName: response.resultBody.firstName,
        lastName: response.resultBody.lastName
      })
    }).catch(() => {})
  }
})

const menuStore = useMenuStore()
</script>
<template>
  <div class="flex h-full">
    <div :class="sidebarExpanded ? 'sidebar-expanded' : 'sidebar-normal'">
      <div class="h-[5rem]">
        <div :style="{display: sidebarExpanded ? 'inline-block' : 'none'}" class="w-[5rem] h-full hover:cursor-pointer hover:bg-blue-300">AAA</div>
        <div class="flex float-right w-[5rem] h-full items-center hover:bg-blue-300" @click="toggleSidebar">
          <div class="w-full text-center hover:cursor-pointer">
            <el-icon :class="sidebarExpanded ? 'sidebar-toggle-arrow' : 'sidebar-toggle-arrow sidebar-toggle-arrow-flipped'">
              <ArrowLeft/>
            </el-icon>
          </div>
        </div>
      </div>
      <SidebarItem
        v-for="(item, index) in menuStore.menuTree"
        :key="'Menu-' + index"
        :item="item"
        :indent="0"/>
    </div>
    <div :class="sidebarExpanded ? 'content-normal' : 'content-wide'">
      <div class="flex w-full h-[5rem] bg-orange-200">
        <div class="flex w-fit h-full text-[1.5rem] items-center">Hello, <span class="text-[1.8rem] font-bold">{{ getFullName() }}</span></div>
        <div
          class="absolute flex right-[1rem] h-[5rem] float-right items-center text-[1.5rem] pl-[1rem] pr-[1rem] hover:bg-orange-300 hover:cursor-pointer"
          @click="logout">Logout</div>
      </div>
      <div class="w-full h-[calc(100%-5rem)] p-[0.2rem]">
        <router-view/>
      </div>
    </div>
  </div>
</template>
<style scoped>
@import 'windowFrame.css';
</style>
